
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.frontendName }}
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
      matchLabels:
        app: {{ .Values.frontend.frontendName }}
        
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.frontendName }}

    spec:
      containers:
        - name: {{ .Values.frontend.frontendName}}
          image: {{ .Values.frontend.image.imgRep }}:{{.Values.frontend.image.imgTag}}
          imagePullPolicy: {{ .Values.frontend.image.imgPullPol }}

      ports:
        - containerPort: {{ .Values.frontend.ports.containerPort}}

      resources:
        requests:
          cpu: {{ .Values.resources.requests.reqCpu }}
          memory: {{ .Values.resources.requests.reqMem }}

        limits:
          cpu: {{ .Values.resources.limits.limitCpu }}
          memory: {{ .Values.resources.limits.limitMem }}

      readinessProbe:
        httpGet:
          path: {{ .Values.frontend.readinessProbe.path }}
          port: {{ .Values.frontend.ports.containerPort }}
        initialDelaySeconds: {{ .Values.frontend.readinessProbe.initDelay }}
        periodSeconds: {{ .Values.frontend.readinessProbe.period }}
        timeoutSeconds: {{ .Values.frontend.readinessProbe.timeout }}
        failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
      

      livenessProbe:
        httpGet:
          path: {{ .Values.frontend.livenessnessProbe.path }}
          port: {{ .Values.frontend.ports.containerPort }}
        initialDelaySeconds: {{ .Values.frontend.livenessnessProbe.initDelay }}
        periodSeconds: {{ .Values.frontend.livenessProbe.period }}
        timeoutSeconds: {{ .Values.frontend.livenessProbe.timeout }}
        failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}



