backend:
  replicas: 1
  backendName: backend
  
  image:
    imgRep: almogbcr/weatherapp-backend
    imgTag: "fc4efa2"
    imgPullPol: ifNotPresent

  ports:
    containerPort: 8000

  resources:
    requests:  
      reqCpu: "100m"
      reqMem: "128Mi"
    limits:
      limitCpu: "500m"
      limitMem: "256Mi"

  readinessProbe:
    path: "/health"
    initDelay: 5
    period: 10
    timeout: 2
    failureThreshold: 3

  livenessProbe:
    path: "/health"
    initDelay: 15
    period: 20
    timeout: 2
    failureThreshold: 3

  
  daily_request_limit: 999

service:
  type_cluster: ClusterIP

frontend:
  replicas: 1
  frontendName: frontend
  
  image:
    imgRep: almogbcr/weatherapp-frontend
    imgTag: "f19f6ab"
    imgPullPol: ifNotPresent
  
  ports:
    containerPort: 80

  resources:
    requests:
      reqCpu: "50m"
      reqMem: "64Mi"
    limits:
      limitCpu: "200m"
      limitMem: "128Mi"
  readinessProbe:
    path: "/"
    initDelay: 3
    period: 10
    timeout: 2
    failureThreshold: 3

  livenessProbe:
    path: "/"
    initDelay: 10
    period: 20
    timeout: 2
    failureThreshold: 3
