apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.backend.backendName }}

  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.backend.backendName }}

  template:
    metadata:
      labels:
        app: {{ .Values.backend.backendName }}
    spec:
      containers:
      - name: {{ .Values.backend.backendName }}
      image: {{ .Values.backend.image.imgRep }}:{{ .Values.backend.image.imgTag }}
      imagePullPolicy: {{ .Values.backend.image.imgPullPol }}

      ports:
        - containerPort: {{ .Values.backend.ports.containerPort }}



      resources:
        requests:
          cpu: {{ .Values.backend.resources.requests.reqCpu }}
          memory: {{ .Values.backend.resources.requests.reqMem }}

        limits:
          cpu: {{ .Values.backend.resources.limits.limitCpu }}
          memory: {{ .Values.backend.resources.limits.limitMem }}

      readinessProbe:
      httpGet:
        path: {{ .Values.backend.readinessProbe.path }}
        port: {{ .Values.backend.ports.containerPort }}
      initialDelaySeconds: {{ .Values.backend.readinessProbe.initDelay }}
      periodSeconds: {{ .Values.backend.readinessProbe.period }}
      timeoutSeconds: {{ .Values.backend.readinessProbe.timeout }}
      failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}


    livenessProbe:
      httpGet:
        path: {{ .Values.backend.livenessProbe.path }}
        port: {{ .Values.backend.ports.containerPort }}
      initialDelaySeconds: {{ .Values.backend.livenessProbe.initDelay }}
      periodSeconds: {{ .Values.backend.livenessProbe.period }}
      timeoutSeconds: {{ .Values.backend.livenessProbe.timeout }}
      failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
      
    env:
      - name: DB_HOST
        valueFrom:
        configMapKeyRef:
          name: postgres-configmap
          key: DB_HOST

      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: postgres-configmap
            key: DB_PORT

      - name: DAILY_REQUEST_LIMIT
        valueFrom:
          configMapKeyRef:
            name: backend-configmap
            key: DAILY_REQUEST_LIMIT

      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_DB

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USER

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD

      - name: OPENWEATHER_API_KEY
        valueFrom:
          secretKeyRef:
            name: backend-api-key
            key: OPENWEATHER_API_KEY
      - name: DATABASE_URL
        value: "postgresql+psycopg://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"





