apiVersion: v1
kind: service

metadata:
  name: {{ .Values.backend.backendName }}
  namespace: {{ .Release.Namespace }}

  spec:
  selector:
      app: {{ .Values.backend.backendName }}
  
  ports:
    - port: {{ .Values.backend.ports.containerPort }}
      targetPort: {{ .Values.backend.ports.containerPort }}
  type: {{ .Values.backend.service.type_cluster }}  
